name: morty_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.1
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
  get_it: ^7.6.7
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1
  dartz: ^0.10.1
  easy_localization: ^3.0.3
  provider: ^6.1.1
  google_fonts: ^6.1.0
  fluttertoast: ^8.2.4
  sqflite: ^2.3.2
  path: ^1.8.0
  internet_connection_checker: ^1.0.0+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  assets:
    - assets/svg/
    - assets/lang/
    - assets/gif/

  uses-material-design: true